### ISSUE TITLE
Issue with erc20 token demo.sh

### ISSUE THREAD

**Issue by tarek-eg** [dfinance-tech/ic-token#1]
Hello,
I am not sure if you are open for feedback on this repo but I have tried to play with the erc20 token and I have seen some issues.
When running the `demo.sh` there's an error message :
`The Replica returned an error: code 3, message: "Canister rrkah-fqaaa-aaaaa-aaaaq-cai has no update method 'storageGenesis'"`

Then 

```
== Dan transfers 40 tokens from Alice to Bob

The Replica returned an error: code 5, message: "Canister rrkah-fqaaa-aaaaa-aaaaq-cai trapped explicitly: arithmetic overflow"
```

Also the numbers logged in console are a bit confusing since you are logging tens but calling functions with thousands.

for example 
```
echo == Dan transfers 40 tokens from Alice to Bob
echo

HOME=$DAN_HOME
eval dfx canister --no-wallet call token transferFrom "'($ALICE_PUBLIC_KEY, $BOB_PUBLIC_KEY, 40000)'"
```

System I am using: macos 11.4 (20F71), MacBook Pro (13-inch, 2019)
```
dfx --version
0.7.2
```

**Comment by ccyanxyz** [comment]
Hi, we welcome feedback and discussions, the purpose of this repo is to provide more and better token canister templates for developers, so actually we are looking forward to collaborating with the community.

`storageGenesis` method is renamed but the demo.sh was not updated, now it's fixed.

The transfer is supposed to fail, we will fix the `arithmetic overflow` problem, improve the error handling.

The amount in the log is 40, the function call parameter is 40000, that's because the token's decimal is 3.
