### ISSUE TITLE
Issue with simple-erc20 demo.sh

### ISSUE THREAD

**Issue by tarek-eg** [dfinance-tech/ic-token#2]
Hello again,

Playing with this demo I have noticed something that I don't quite understand

```
== Dan grants Bob permission to spend 100 of this tokens: Should fail, dan only has 99 tokens

(true)
```
Shouldn't this call fail and returns (false) or I am missing something?

Also when running the demo.sh I got this warning
```
ic-token/simple-erc20/src/token.mo:29.44-29.64: warning [M0155], operator may trap for inferred type
  Nat
```

System I am using: macos 11.4 (20F71), MacBook Pro (13-inch, 2019)
```
dfx --version
0.7.2
```
Thanks,

**Comment by ccyanxyz** [comment]
Thanks for the feedback.

The `approve` actually should succeed, because approve does not check balance, so it returns true, it is normal, the "Should fail" comment is wrong, forget to delete it.

The warning is because we didn't give a type for the variable.

These problems have been fixed in this [commit](https://github.com/dfinance-tech/ic-token/commit/2a4163de2356985a60d034c699c589a36915159d).
