### ISSUE TITLE
Improvement suggestions

### ISSUE THREAD

**Issue by ferencdg** [dfinance-tech/ic-token#4]
Hi, I would like to suggest some improvments.

1. The TransactionReceipt and ApprovalReceipt structures are not standardized. This means clients cannot uniformly be notified, if an ERC-20 transaction or ERC-20 approval happened.

2. The method signatures for some of the methods are incorrect. For example  transfer and approve methods return only a bool, so there is no way for a client to know the transaction id or approval id. In fact transfer should return a TransactionReceipt while approve should return an ApprovalReceipt.

3. There are methods like burn or mint that really shouldn't be in a standard, as for most tokens they are meaningless. Most ERC-20  tokens have a constant supply of tokens and cannot meaningfully implement a method like that. Those methods could be part of an other standard on top of ERC-20.

4. We should be more specific about the schemantics of the approve method. For example, let's say I have a token balance 100 tokens. In this case, if I want, then it is allowed for me to approve withdrawals greater than my balance let's say 150. 

5. Rust code needs improvments for example your mint method allows anyone to mint money. Token supply and other data should be in the stable memory and not initialized every time imho.

**Comment by ccyanxyz** [comment]
Thanks for the feedback.

About 1 & 2, we are going to add better error handling than just booleans.

About 3, we try to provide a complete token template for developers, so we included the mint & burn functions in the current implementations, devs can choose to keep them or not when they use it to deploy their own tokens. 

About 4, are you saying we should limit the max amount a user can approve according to his/her balance? So if I have 100 tokens, then the max amount I can approve is 1.5 * balance which is 150? This will prevent the unlimited approval problem on Ethereum, more secure, but less user-friendly, because I may have to approve again when the allowance is not enough.

About 5, fixing it now.

**Comment by ferencdg** [comment]
thank you, regarding point 4 I am suggesting to do the same as Etherum and allow unlimited approval. We should just mention this in the token standard that it is allowed, so every token will implement it the same way. 

Regarding point 3, maybe we could just mention that that those points are not part of the (narrower) ERC-20 standard, but they can be implemented on top of that. So people would now what it means to have an ERC-20 compatible standard (don't have to second guess about those 4 methods)

**Comment by ccyanxyz** [comment]
Agreed

**Comment by flyq** [comment]
> 5\. Rust code needs improvments for example your mint method allows anyone to mint money. Token supply and other data should be in the stable memory and not initialized every time imho.

it fixed in https://github.com/dfinance-tech/ic-token/blob/2dd08eaf60/rust/src/main.rs

**Comment by ferencdg** [comment]
discussed this issue and many more, this ticket became very outdated, so closing it
